name: stylus
version: 0.1.2
author: Wilker Lucio <wilkerlucio@gmail.com>
description: Stylus CLI wrapper for Dart
homepage: https://github.com/wilkerlucio/dart-stylus
dependencies:
  barback: '>=0.11.1'
  editor_build: '>=0.0.4 <=1.0.0'
  path: '>=1.0.0 <2.0.0'
  html5lib: '>=0.9.2'
dev_dependencies:
  unittest: any
